# Generated by Django 2.2.4 on 2019-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=50, unique=True)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=2)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('unknown', 'unknown')], default='unknown', help_text='Age', max_length=16)),
                ('fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('unknown', 'unknown')], default='unknown', help_text='Primary Fur Color', max_length=50)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('unknown', 'unknown')], default='unknown', help_text='Location', max_length=50)),
                ('specific_location', models.CharField(blank=True, help_text='Specific Location', max_length=100)),
                ('running', models.BooleanField(default=False, help_text='Whether the squirrel is running')),
                ('chasing', models.BooleanField(default=False, help_text='whether the squirrel is chasing')),
                ('climbing', models.BooleanField(default=False, help_text='whether the squirrel is climbing')),
                ('eating', models.BooleanField(default=False, help_text='whether the squirrel is eating')),
                ('foraging', models.BooleanField(default=False, help_text='whether the squirrel is foraging')),
                ('other_activities', models.CharField(blank=True, help_text='Other actions of squirrel besides running, chasing, climbing, eating and foraging', max_length=100)),
                ('kuks', models.BooleanField(default=False, help_text='Whether the squirrel is in kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Whether the squirrel is in quaas')),
                ('moans', models.BooleanField(default=False, help_text='Whether the squirrel is in moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Whether the squirrel has tail flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Whether the squirrel has tail twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Whether the squirrel approaches human or not')),
                ('indifferent', models.BooleanField(default=False, help_text='Whether the squirrel is indifferent or not')),
                ('runs_from', models.BooleanField(default=False, help_text='Whether the squirrel runs from human or not')),
            ],
        ),
    ]
