# Generated by Django 2.2.4 on 2019-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Whether the squirrel approaches human or not'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False, help_text='whether the squirrel is chasing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False, help_text='whether the squirrel is climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default=False, help_text='whether the squirrel is eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default=False, help_text='whether the squirrel is foraging'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Whether the squirrel is indifferent or not'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Whether the squirrel is in kuks'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=False, help_text='Whether the squirrel is in moans'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other actions of squirrel besides running, chasing, climbing, eating and foraging', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Whether the squirrel is in quaas'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False, help_text='Whether the squirrel is running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Whether the squirrel runs from human or not'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='Whether the squirrel has tail flags'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='Whether the squirrel has tail twitches'),
        ),
    ]
